### ISSUE TITLE
Cannot read property 'onunload' of undefined

### ISSUE THREAD

**Issue by sjungwirth** [StephanHoyer/mithril-node-render#16]
Hi I am getting the error below because mithril-node-render assumes controller function returns an object which is not required.

    TypeError: Cannot read property 'onunload' of undefined
        at render (node_modules/mithril-node-render/index.js:87:14)

The easy fix for me is to add `|| {}` to the return value of view.controller()

    var scope = view.controller() || {};

**Comment by StephanHoyer** [comment]
Feel free to create a pr.

**Comment by StephanHoyer** [comment]
should be fixed in 0.3.2
