### ISSUE TITLE
Null "value" gets rendered

### ISSUE THREAD

**Issue by jrvidal** [StephanHoyer/mithril-node-render#18]
Example:

```js
var m = require("mithril"),
    render = require("mithril-node-render"),

    html = render(
        m("input[type=text]", {
            value: null
        })
    );

console.log(html); // <input type="text" value="null">
```

This is inconsistent with DOM rendering, where `null` values are equivalent to the empty string.

**Comment by StephanHoyer** [comment]
hi @jrvidal,

Thanks for reporting. This is an easy fix.

Do you want to create a PR for this?

regards
Stephan

**Comment by jrvidal** [comment]
Sure. I didn't do it right away because I'm not sure about the scope of the change. Can you think of any other attributes that would interpret `null` as "don't render"?

**Comment by StephanHoyer** [comment]
I think all attributes should not be rendered if attribute is null.

Refer to the way mithril renders this.
