### ISSUE TITLE
Escaping HTML in attribute values

### ISSUE THREAD

**Issue by codeclown** [StephanHoyer/mithril-node-render#23]
Is there a reason for escaping HTML in attribute values? Talking about [this line](https://github.com/StephanHoyer/mithril-node-render/blob/b39668513933d6ef9e21d048efd0b096c469c956/index.js#L60).

Some CMS/ESP solutions use tags for serving dynamic content (it stinks but is true). Escaping attribute values makes it impossible to use these tags inside attributes.

What I'm talking about (made-up example):

```
<a href="<span random-cms='asset_url'></span>">Download asset</a>
```

I'm interested to know if there's a reason the content is escaped. If there is a solid reason, maybe it could be considered to add an option for leaving attribute values unescaped?

Either way, I can provide a tested pull request once there is a conclusion on this issue.

**Comment by StephanHoyer** [comment]
There is no special reason why this is escaped. Just thought it's invalid to not do so. Also I thought there is a security issue not escaping it.

I think at least the quotes have to be escaped.

**Comment by codeclown** [comment]
Reading [the HTML spec](http://www.w3.org/TR/2011/WD-html5-20110525/elements.html#attributes), it seems that any character is valid inside attribute values. I'm not sure if that means they should be escaped, though.

That being said, having unescaped double quotes is definitely not valid (assuming double quotes are used for wrapping the value). Somehow I don't like the idea of only escaping double quotes, it seems a bit... hacky. What do you think? Might be better to raise an exception in case of a double quote. In any case, allowing them unescaped by default is probably not a good idea. Escaping is probably most often the expected behaviour, even.

Having this as an option might be the way to go. Even better if it could be defined per element, e.g.

```
m('div', { id: m.trust('foobar') })
```

That [seems to work](https://jsfiddle.net/2s2Lmkgt/) okay in Mithril still. It's a bit hacky as well though, since it's not what `m.trust` was intended for. Introducing some other way (e.g. special properties) is probably a bad idea.

So, I guess my proposal would be to allow it as a universal option, something like this:

```
render(component, { escapeAttributeValues: false });
```

Would be great to hear the opinion of someone smarter than me.

**Comment by StephanHoyer** [comment]
yep. feel free to implement it that way.
