### ISSUE TITLE
not support promise ?

### ISSUE THREAD

**Issue by cheft** [StephanHoyer/mithril-node-render#28]
not support promise ?

**Comment by StephanHoyer** [comment]
can you be more specific please?

**Comment by cheft** [comment]
Run the [mithril demo](http://mithril.js.org/index.html), throw error

         ctrl.pages().map(function(page) {
           ^
    TypeError: ctrl.pages is not a function

because ctrl.pages() is promise object, want to support!

**Comment by StephanHoyer** [comment]
Can you please show the full code. I think the problem is unrelated to mithril-node-render

**Comment by StephanHoyer** [comment]
Will close this for now.

Feel free to reopen, if this is still a problem.
