### ISSUE TITLE
can you move the blog about isomorphic mithril applications to the wiki page

### ISSUE THREAD

**Issue by ginus** [StephanHoyer/mithril-node-render#8]
the blog is https://gist.github.com/StephanHoyer/bddccd9e159828867d2a
It will more convenient if you move it to the project wiki

**Comment by StephanHoyer** [comment]
Yes I can, but what's wrong with gist?

**Comment by ginus** [comment]
In China, the "gist.github.com" is blocked.

**Comment by StephanHoyer** [comment]
Thats too bad.

[Here](https://github.com/StephanHoyer/mithril-isomorphic-example/wiki/Inspirational-blog-post) it is

**Comment by ginus** [comment]
thanks greet!
