### ISSUE TITLE
Object.keys required for trusted content?

### ISSUE THREAD

**Issue by ciscoheat** [StephanHoyer/mithril-node-render#9]
Hi, I'm porting your nice code to Haxe, and I see that you are using `Object.keys(view)` to render trusted content. Is there a specific reason for this, since `view` is always(?) a String object in this case `Object.keys` gives some problem in Haxe so I'm using the string value directly and it seems to work, but I wanted to be sure.

**Comment by StephanHoyer** [comment]
At this point I really don't understand, what i've been done here ;)

I'll look into it.

**Comment by StephanHoyer** [comment]
Ok, now I figured it out. If I log the result of `m.trust('<foo></foo>')` i get something like this.

```
{ '0': '<',
  '1': 'f',
  '2': 'o',
  '3': 'o',
  '4': '>',
  '5': '<',
  '6': '/',
  '7': 'f',
  '8': 'o',
  '9': 'o',
  '10': '>',
  '$trusted': true }
```

I will try to find out whats happening here.

**Comment by StephanHoyer** [comment]
turns out I could simply cast to string.

**Comment by StephanHoyer** [comment]
Just found a pretty bad security flaw. Html-content was not quoted.

Maybe you should update your version too.

**Comment by ciscoheat** [comment]
Yes, I just outputted the trusted value as a string, it worked fine.
Thanks for the security notice, will fix. :)

**Comment by StephanHoyer** [comment]
Do you have a link to your project?

**Comment by ciscoheat** [comment]
Yes, it's the same project as the Mithril library for Haxe: https://github.com/ciscoheat/mithril-hx
